import { makeStyles } from '@mui/styles';

const useStyles = makeStyles(() => ({
  transferCardStyle: {
    color: '#F5F9FC',
    fontFamily: 'Abar Mid',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 'normal',
    borderRadius: '12px',
    overflow: 'hidden',
    marginBottom: '32px',
  },
  cardInfo: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#0D446B',
    padding: '0px 11px',
    paddingLeft: '0',
    gap: '8px',
  },
  banksCardTitle: {
    color: ' #FDFDFD',
    textAlign: 'right',
    fontFamily: 'Abar Low',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
    letterSpacing: '-0.5px',
  },
  cardNo: {
    color: '#FDFDFD',
    textAlign: 'right',
    fontFamily: 'Abar Mid',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
  },
  inventory: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8.5px 16px',
    backgroundColor: '#102243',
  },
  amountFontStyle: {
    color: '#F5F9FC',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
  },
  assetsList: {
    gap: '16px',
    maxHeight: '50%',
    display: 'grid',
    padding: '0',
    gridTemplateColumns: 'repeat(2, 1fr)',
    height: '100%',
  },
  assetItem: {
    display: 'flex',
    width: '100%',
    padding: '0 16px',
    flexDirection: 'column',
    gap: '6px',
    flexShrink: 0,
    borderRadius: '10px',
    overflow: 'hidden',
    height: '100%',
  },
  assetTitle: {
    fontWeight: '550',
    fontSize: '18px',
    color: 'white',
    margin: '0',
    padding: '0',
  },
  progressBar: {
    width: '100%',
    height: '6px',
    backgroundColor: '#eee',
    borderRadius: '10px',
    overflow: 'hidden',
  },
  progressValueStyle: {
    backgroundColor: '#aaa',
    height: '100%',
  },
}));

export default useStyles;
