import { makeStyles } from '@mui/styles';

export const useDepositStyles = makeStyles(() => ({
  depositContainer: {
    width: '100%',
    padding: '27px 8px',
    height: '100%',
    position: 'relative',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    color: '#F5F9FC',
    textAlign: 'right',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
    justifyContent: 'space-between',
    alignItems: 'stretch',
  },
  formGroup: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: ' 8px',
    border: '1px solid  #626F86',
    padding: '11px 8px',
    textWrap: 'nowrap',
  },
  formInputStyle: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'transparent',
    border: 'none',
    outLine: 'none',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 'normal',
    color: '#F5F9FC',
    textAlign: 'right',
    textOverflow: 'ellipsis',
  },
  submitButton: {
    width: '100%',
    padding: '8px 0',
    borderRadius: '10px',
    color: ' #12284C',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: 'normal',
    border: 'none',
    outline: 'none',
    cursor: 'pointer',
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
  },
}));
